name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry install
        pip install ruff

    - name: Check code formatting with ruff
      run: |
        ruff format --check .

    - name: Check code style with ruff
      run: |
        ruff check .

    - name: Run tests
      run: |
        poetry run pytest